name: Cron Create Issues

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 4,16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get today's date
        id: date
        run: |
          echo "::set-output name=today::$(date "+%Y-%m-%d")"

      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.DSR_GITHUB_TOKEN }}
          title: ${{ steps.date.outputs.today }}
          labels: ${{ steps.date.outputs.today }} 

